---
title: "Causal Relationships in the Quantitative Social Sciences"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In quantitative political research we are generally interested in explaining the causes of effects. This week introduces the basic logic of causal relationships, their formal representation through directed acyclic graphs (DAGs), and different types of estimands that aid us in answering our research questions and arriving at valid conclusions in political science.

## Tuesday, September 13th, 2022

-   Bueno de Mesquita, Ethan and Anthony Fowler. 2021. "Causation: What is it and What is it Good for?" in *Thinking Clearly with Data*. Princeton University Press, pp. 34--52

-   Rohrer, Julia M. 2018. "Thinking Clearly About Correlations and Causation: Graphical Causal Models for Observational Data." *Advances in Methods and Practices in Psychological Science* 1(1): 27--42. doi: [10.1177/2515245917745629](https://doi.org/10.1177/2515245917745629).

## Thursday, September 15th, 2022

-   No class as I will be in Montréal for a conference. The preliminary research question assignment is due via Canvas on Friday, September 16th by 11:59PM.

## Suggested Readings

-   Huntington-Klein, Nick. 2022. "Causal Paths and Closing Back Doors" in *The Effect: An Introduction to Research Design and Causality*. Boca Raton, FL: CRC Press, 116--128. [https://theeffectbook.net/ch-CausalPaths.html](https://theeffectbook.net/ch-CausalPaths.html)
