---
title: "Quasi-Experimental Designs I"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In many if not most cases in political science and economics, baseline random assignment of the treatment is either impractical or infeasible due to ethical, financial, or other considerations. Faced with this reality, social scientists often rely on quasi-experimental approaches to estimate causal effects. This week we will explore alternatives to experimental designs that attempt to achieve baseline random assignment, their core assumptions, and some of their limitations focusing on difference in difference and regression discontinuity designs in particular.

### Tuesday, November 15th, 2022

- Bueno de Mesquita, Ethan and Anthony Fowler. 2021. "Difference in Differences Designs" in *Thinking Clearly with Data*. Princeton University Press, pp. 266--288

- Latura, Audrey and Ana Catalano Weeks. 2022. "Corporate Board Quotas and Gender Equality Policies in the Workplace." *American Journal of Political Science*. doi/dataverse: [10.1111/ajps.12709](https://doi.org/10.1111/ajps.12709); [10.7910/DVN/WJINZP](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/WJINZP)

### Thursday, November 17th, 2022

- Bueno de Mesquita, Ethan and Anthony Fowler. 2021. "Regression Discontinuity Designs" in *Thinking Clearly with Data: A Guide to Quantitative Reasoning and Analysis*. Princeton University Press, pp. 243--264

- Sevi, Semra. 2022. "Is Incumbency Advantage Gendered?" *Legislative Studies Quarterly*. doi/dataverse: [10.1111/lsq.12376](https://doi.org/10.1111/lsq.12376); [10.7910/DVN/VHFO7V](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VHFO7V)

### Reccomended Readings

- Huntington-Klein, Nick. 2022. "Difference-in-Differences" in *The Effect: An Introduction to Research Design and Causality*. Boca Raton, FL: CRC Press, pp. 435--467. [https://theeffectbook.net/ch-DifferenceinDifference.html](https://theeffectbook.net/ch-DifferenceinDifference.html)

- Imai, Kosuke, and Song Kim. 2021. "On the Use of Two-Way Fixed Effects Regression Models for Causal Inference with Panel Data." *Political Analysis* 29(3): 405--415. doi: [10.1017/pan.2020.33](https://doi.org/10.1017/pan.2020.33)

- Huntington-Klein, Nick. 2022. "Regression Discontinuity" in *The Effect: An Introduction to Research Design and Causality*. Boca Raton, FL: CRC Press, pp. 505--554. [https://theeffectbook.net/ch-RegressionDiscontinuity.html](https://theeffectbook.net/ch-RegressionDiscontinuity.html)
