---
title: "Multiple Regression II"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Continuing our introduction to regression, this week we'll take a more detailed look at the logic of regression adjustment as a means of dealing with confounding. Moving beyond the framework of constant linear relationships, we'll explore more principled approaches to analyzing non-linear relationships and questions of classification that are distinct from regression.

### Tuesday, October 25th, 2022

- Bueno de Mesquita, Ethan and Anthony Fowler. 2021. "Controlling for Confounders" in *Thinking Clearly with Data*. Princeton University Press, pp. 193--217

- Cinelli, Carlos, Andrew Forney, and Judea Pearl. 2022. "A Crash Course in Good and Bad Controls." *Sociological Methods \& Research*: 1--34. doi: [10.1177/00491241221099552](https://doi.org/10.1177/00491241221099552)

### Thursday, October 27th, 2022

- Johnson, Alicia A., Miles Q. Ott, Mine Dogucu. 2022. ["Chapter 13: Logistic Regression"](https://www.bayesrulesbook.com/chapter-13.html) in *Bayes Rules! An Introduction to Applied Bayesian Modeling*. Boca Raton, FL: CRC Press.

- Problem Set 3 is due via Canvas on Sunday, October 30th by 11:59PM

### Recommended Readings

- Mood, Carina. 2010. "Logistic Regression: Why We Cannot Do What We Think We Can Do, and What We Can Do About It." *European Sociological Review* 26(1): 67–82. doi: [10.1093/esr/jcp006](https://doi.org/10.1093/esr/jcp006)

- Clarke, Kevin A., Brenton Kenkel, and Miguel R. Rueda. 2018. "Omitted Variables, Countervailing Effects, and the Possibility of Overadjustment." *Political Science Research and Methods* 6(2): 343--354. doi/dataverse: [10.1017/psrm.2016.46](https://doi.org/10.1017/psrm.2016.46); [10.7910/DVN/BSKHUF](https://doi.org/10.7910/DVN/BSKHUF)
