---
title: "Prediction and Forecasting for Political Research"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We've covered a great deal over the course of the semester, focusing mainly on strategies for causal inference and probabilistic reasoning. To conclude this course, we'll briefly turn our attention to a somewhat different inferential goal and discuss the use of predictive modeling and machine learning in the quantitative social sciences.

### Tuesday, November 29th, 2022

- Cranmer, Skyler J., and Bruce A. Desmarais. 2017. "What Can We Learn from Predictive Modeling?" *Political Analysis* 25(2): 145–-66. doi: [10.1017/pan.2017.3](https://doi.org/10.1017/pan.2017.3)

- Fariss, Christopher J., and Zachary M. Jones. 2018. "Enhancing Validity in Observational Settings When Replication Is Not Possible." *Political Science Research and Methods* 6(2): 365–-80. doi/dataverse: [10.1017/psrm.2017.5](https://doi.org/10.1017/psrm.2017.5); [10.7910/DVN/O2BK85](http://dx.doi.org/10.7910/DVN/O2BK85)

### Thursday, December 1st, 2022

- No Class. Work on your final papers and research presentations.
