---
title: "Multiple Regression I"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Regression models are ubiquitous in political science and serve as the primary workhorse for statistical inference. This week we will continue our introduction to the foundations of applied statistics in political science and the use of regression as an approach to estimating and describing relationships. We'll also more concretely discuss the assumptions necessary for valid inference.

### Tuesday, October 18th, 2022

- Bueno de Mesquita, Ethan and Anthony Fowler. 2021. "Samples, Uncertainty, and Statistical Inference" in *Thinking Clearly with Data*. Princeton University Press, pp. 94--112

- Aronow, Peter M., and Cyrus Samii. 2016. "Does Regression Produce Representative Estimates of Causal Effects?" *American Journal of Political Science* 60 (1): 250–267. doi: [10.1111/ajps.12185](https://doi.org/10.1111/ajps.12185); dataverse: [10.7910/DVN/29098](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/29098)

### Thursday, October 20th, 2022

- Bueno de Mesquita, Ethan and Anthony Fowler. 2021. "Why Correlation Doesn't Imply Causation" in *Thinking Clearly with Data*. Princeton University Press, pp. 160--192

- Johnson, Alicia A., Miles Q. Ott, Mine Dogucu. 2022. ["Chapter 9: Simple Normal Regression"](https://www.bayesrulesbook.com/chapter-9.html) in *Bayes Rules! An Introduction to Applied Bayesian Modeling*. Boca Raton, FL: CRC Press.

- Problem Set III is due via Canvas on Sunday, October 23rd by 11:59PM

### Reccomended Readings

- Huntington-Klein, Nick. 2022. "Regression" in *The Effect: An Introduction to Research Design and Causality*. Boca Raton, FL: CRC Press, pp. 179--266. [https://theeffectbook.net/ch-StatisticalAdjustment.html](https://theeffectbook.net/ch-StatisticalAdjustment.html)

- Johnson, Alicia A., Miles Q. Ott, Mine Dogucu. 2022. ["Chapters 10-11"](https://www.bayesrulesbook.com/chapter-10.html) in *Bayes Rules! An Introduction to Applied Bayesian Modeling*. Boca Raton, FL: CRC Press.


