---
title: "Probabilistic Reasoning and Applied Bayesian Inference"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Continuing with our brief introduction to inferential statistics, this week we dive more concretely into the application of probability theory and Bayesian inference in the contemporary social sciences as a powerful and principled tool for expressing and quantifying uncertainty.

### Tuesday, October 11th, 2022

- Johnson, Alicia A., Miles Q. Ott, Mine Dogucu. 2022. ["Chapters 1 and 2"](https://www.bayesrulesbook.com/chapter-1.html) in *Bayes Rules! An Introduction to Applied Bayesian Modeling*. Boca Raton, FL: CRC Press.

### Thursday, October 13th, 2022

- Johnson, Alicia A., Miles Q. Ott, Mine Dogucu. 2022. ["Chapter 4: Balance and Sequentiality in Bayesian Analyses"](https://www.bayesrulesbook.com/chapter-4.html) in *Bayes Rules! An Introduction to Applied Bayesian Modeling*. Boca Raton, FL: CRC Press.

- Allen, Michael A., et al. 2020. "Outside the Wire: U.S. Military Deployments and Public Opinion in Host States." *American Political Science Review* 114(2): 326–41. doi/dataverse: [10.1017/S0003055419000868](https://doi.org/10.1017/S0003055419000868); [10.7910/DVN/VCE7KN](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VCE7KN)

### Reccomended Readings

- Gelman, Andrew, Jennifer Hill, and Aki Vehtari. 2021. *Regression and Other Stories*. Cambridge University Press, pp. 113--182

- Western, Bruce, and Simon Jackman. 1994. "Bayesian Inference for Comparative Research." *American Political Science Review* 88(2): 412–423. doi: [10.2307/2944713](https://doi.org/10.2307/2944713)