---
title: "Quasi-Experimental Designs II"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The approaches to estimating causal effects we've examined thus far rest upon the assumption of *strict exogeniety* which tends to fail spectacularly in the context of observational data and inhibits our ability to make causal claims outside of experimental settings. This week we turn our focus to recent developments in political science that draw on a set of weaker identifying assumptions known as *sequential ignorability* to identify treatment effects and examine causal mechanisms.

### Tuesday, November 22nd, 2022

- Kurtz, Marcus J., and Adam Lauretig. 2022. "Does Free-Market Reform Induce Protest? Selection, Post-Treatment Bias, and Depoliticization." *British Journal of Political Science* 52(2): 968-–976. doi/dataverse: [10.1017/S0007123420000605](https://doi.org/10.1017/S0007123420000605); [10.7910/DVN/WU2WSE](https://doi.org/10.7910/DVN/WU2WSE)

- Ladam, Christina, Jeffrey J. Harden, Jason H. Windett. 2018. "Prominent Role Models: High-Profile Female Politicians and the Emergence of Women as Candidates for Public Office." *American Journal of Political Science*, 62 (2): 369--381. doi/dataverse: [10.1017/10.1111/ajps.12351](https://doi.org/10.1111/ajps.12351); [10.7910/DVN/D5DEHM](http://doi.org/10.7910/DVN/D5DEHM)

### Thursday, November 24th, 2022

- No class. Thanksgiving Break

- Problem Set V is due via Canvas on Sunday, November 27th by 11:59PM

### Reccomended Readings

- Blackwell, Matthew and Adam Glynn. 2018. "How to Make Causal Inferences with Time-Series Cross-Sectional Data under Selection on Observables." *American Political Science Review* 112 (4): 1067--1082. doi/dataverse: [10.1017/S0003055418000357](https://doi.org/10.1017/S0003055418000357); [10.7910/DVN/SFBX6Z](https://doi.org/10.7910/DVN/SFBX6Z)
